name: 'build-and-test'
description: 'build and test the whole repo'
inputs:
outputs:
runs:
  using: "composite"
  steps:
    - name: Build
      run: pnpm run build
      
    - name: Test
      run: pnpm run test
