name: 'set-environment'
description: 'Install the pacmage manager and install the dependency'
inputs:
outputs:
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7

    - name: Install dependency
      run: pnpm install